
name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight every day
  workflow_dispatch: # Allows manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: gurpal-saghi-9
          outputs: dist/snake.svg

      - name: Push the animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
